config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :conversations
  resources :user_organizations
  resources :topics
  resources :organizations
  resources :moderators
  resources :communities
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :organizations do 
    resources :topics do
      resources :posts do     #These are for communities. Show all the posts in that community, irrespective of who follows who etc.
        resources :comments, only: [:create, :destroy]
        member do
          post :repost
        end
      end
    end
  end

  resources :feed
  
  resources :posts do         #All these are based on your feed. Can't show everything in the world at once
    patch 'moderation', on: :member
    resources :comments, only: [:create, :destroy]
    member do
      post 'update_options'
      get 'see_votes'
      post :repost
    end
  end
  

  resources :profiles do
    collection do
      get 'search'
    end
  end

  resources :likes, only: :create
  resources :connections do
    patch 'accept', on: :member
    resources :topics
  end

  resources :moderators
  get '/moderator/show_all/:user_id', to: 'moderators#show_all', as: 'moderator_show_all'


  resources :communities do
      post 'join_community', on: :collection
      resources :topics
  end

  resources :conversations do
    resources :messages
  end

  post 'switch_organization/:organization_id/:topic_id', to: 'organizations#switch_organization', as: :switch_organization
  post 'send_connection', to: 'connections#send_connection', as: 'send_connection'
  post '/add_moderator_request', to: 'moderators#add_moderator_request', as: 'add_moderator_request'
  patch '/add_moderator', to: 'moderators#add_moderator', as: 'add_moderator'
  get 'repost_posts', to: 'posts#repost_post', as: 'repost_posts'
  patch '/submit_repost', to: 'posts#submit_repost', as: 'submit_repost'
  get 'choose_posts', to: 'posts#choose', as: 'choose'

  #devise_for :users
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  root to: "feed#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :post
  belongs_to :parent_comment, class_name: 'Comment', optional: true
  has_many :children, class_name: "Comment", foreign_key: "parent_comment_id"
end

app/models/community.rb
class Community < ApplicationRecord
  belongs_to :organization
  belongs_to :topic
  belongs_to :privacy
  has_many :moderators
end

app/models/connection.rb
class Connection < ApplicationRecord
  belongs_to :followed, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
    belongs_to :recipient, foreign_key: :recipient_id, class_name:       'User'
    has_many :messages, dependent: :destroy
    validates_uniqueness_of :sender_id, scope: :recipient_id
    scope :between, -> (sender_id, recipient_id) do 
        where("(conversations.sender_id = ? AND   conversations.recipient_id =?) OR (conversations.sender_id = ? AND conversations.recipient_id =?)", sender_id, recipient_id, recipient_id, sender_id)
    end

end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :likeable, polymorphic: true
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
    belongs_to :conversation
    belongs_to :user
    validates_presence_of :body, :conversation_id, :user_id
end

app/models/moderator.rb
class Moderator < ApplicationRecord
  belongs_to :user
  belongs_to :organization, optional: true
  has_many :communities
end

app/models/moderator_request.rb
class ModeratorRequest < ApplicationRecord
  belongs_to :user
  belongs_to :topic
  belongs_to :organization
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :users
    has_many :communities
    has_many :user_organizations 
    has_many :moderators
    belongs_to :privacy
end

app/models/post.rb
class Post < ApplicationRecord
  include Likeable
  belongs_to :user
  belongs_to :post, optional: true
  has_many :comments
  has_many :moderators
  belongs_to :organization
  has_and_belongs_to_many :topics
  validates :body, length: { maximum: 800 }, allow_blank: false, unless: :post_id

  before_create :initialize_reposted_at

  def post_type
    if post_id? && body?
      "quote-post"
    elsif post_id?
      "repost"
    else
      "post"
    end
  end

  private

  def initialize_reposted_at
    self.reposted_at = self.created_at
  end

end

app/models/privacy.rb
class Privacy < ApplicationRecord
    has_many :organizations
end

app/models/topic.rb
class Topic < ApplicationRecord
    belongs_to :parent, class_name: 'Topic', optional: true
    has_many :children, class_name: 'Topic', foreign_key: 'parent_id'
    has_and_belongs_to_many :posts

    # Instance method to get the full pathname
    def full_path_name
        # Split the topic_path into individual topic IDs
        path_ids = self.topic_path.split('/')

        # Map the IDs to their corresponding topic names
        path_names = path_ids.map do |id|
        topic = Topic.find_by(id: id)
        topic ? topic.topic_name : nil
        end

        # Join the names with slashes and return the full path name
        path_names.compact.join('/')
    end
end

app/models/user.rb
class User < ApplicationRecord
  pay_customer

  has_person_name

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable  #, :confirmable
  has_many :posts
  has_many :user_organizations
  has_many :user_communities
  validates_uniqueness_of :username

  has_one_attached :profile_image

  def joined_community?(organization, topic)
    user_community = UserCommunity.find_by(user: self, organization: organization, topic: topic)
    return false unless user_community
    user_community.part_of
  end
  
end

app/models/user_community.rb
class UserCommunity < ApplicationRecord
  belongs_to :user
  belongs_to :organization
  belongs_to :topic
end

app/models/user_organization.rb
class UserOrganization < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/models/vote.rb
class Vote < ApplicationRecord
    belongs_to :user
    belongs_to :post
end

app/helpers/feed_helper.rb
module FeedHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/shared/_flash_notice.html.erb
<% unless flash[:post_errors] %>
  <% flash.each do |type, message| %>
    <div class="<%= flash_classes(type) %>">
      <%= message %>
    </div>
  <% end %>
<% end %>

app/views/shared/_head.html.erb
 <head>
  <title>
    <%= content_for?(:title) ? yield(:title) : "Inntwine" %>
  </title>

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag  'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag "application", defer: true %>
  <%#= javascript_include_tag 'https://js.stripe.com/v3/', 'data-turbolinks-track': 'reload' %>
</head>

app/views/shared/_navbar.html.erb
<nav class="flex flex-wrap items-center justify-between py-3 text-gray-700 bg-white container mx-auto lg:px-0 px-4 <%= nav_classes %>" data-controller="nav">
  <div class="flex items-center mr-6 flex-no-shrink">
     <%= link_to root_path, class:"link text-xl tracking-tight font-black" do %>
      <span class="sr-only">Add your app name here</span>
      <%# Remove this logo and add your own %>
      <svg fill="none" class="w-9 h-9" height="512" viewBox="0 0 512 512" width="512" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink"><linearGradient id="a" gradientUnits="userSpaceOnUse" x1="56" x2="463" y1="46" y2="465"><stop offset="0" stop-color="#8038ed"/><stop offset="1" stop-color="#3a0092"/></linearGradient><path d="m0 0h512v512h-512z" fill="#fff"/><rect fill="url(#a)" height="512" rx="110" width="512"/><g stroke="#fff"><circle cx="190" cy="302" r="79.5" stroke-opacity=".9" stroke-width="25"/><circle cx="254" cy="377" r="34" stroke-opacity=".8" stroke-width="10"/><circle cx="282" cy="227" r="106" stroke-width="50"/></g></svg>
    <% end %>
  </div>
  <div class="block lg:hidden">
    <%# Mobile nav toggle %>
    <button class="flex items-center p-2 -mr-1 rounded-lg focus:bg-gray-100" data-action="click->nav#toggleMenu touch->nav#toggleMenu">
      <svg class="stroke-current text-gray-500 w-7 h-7" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><title>Menu</title><g fill="none"><path d="M4 6h16M4 12h8m-8 6h16" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"></path></g></svg>
    </button>
  </div>
  <div class="items-center w-full text-center lg:flex-1 lg:flex lg:text-left pt-2 lg:pt-0 hidden" data-nav-target="menu">
    <div class="lg:flex-grow">
      <%= link_to "Basic Link", "#", class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
    </div>
    <div class="items-center block w-full mt-2 text-center lg:flex lg:flex-row lg:flex-1 lg:mt-0 lg:text-left lg:justify-end">
      <div><%# More links can go here %></div>
      <% if user_signed_in? %>
        <%= link_to "Edit account", edit_user_registration_path, class: "p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= button_to "Log out", destroy_user_session_path, method: :delete, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block" %>
        <%= link_to "Sign up", new_user_registration_path, class:"p-3 hover:bg-gray-50 transition ease duration-300 rounded-lg text-center focus:bg-gray-100 lg:inline-block block lg:ml-2" %>

        <span class="h-5 w-px bg-gray-200 mx-3"></span>

        <%= link_to "https://github.com/justalever/kickoff_tailwind", target: :_blank, class: "group lg:ml-2 flex justify-center" do %>
        <svg class="fill-current text-gray-400 group-hover:text-gray-600" xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"><path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z"/></svg>
        <% end %>
      <% end %>
    </div>
  </div>
</nav>

app/views/shared/_nested_noturbo_topic.html.erb
<!-- app/views/shared/_nested_noturbo_topic.html.erb -->

<% if topic.present? && topic.children.present? %>
  <li class="sidebar-item cursor-pointer" data-item-id="<%= topic.id %>">
    <span class="flex items-center justify-between">
      <span class="sidebar-heading">
        <span class="arrow-icon border-solid border border-t-4 border-transparent cursor-pointer" onclick="toggleChildren(this)">&#9654;</span>
        <%= link_to topic.topic_name, communities_path(topic_id: topic.id), class: "community-link", data: { turbo: false}  %>
      </span>
    </span>
    <ul class="sub-items hidden pl-4">
      <% topic.children.each do |child_topic| %>
        <%= render 'shared/nested_noturbo_topic', topic: child_topic %>
      <% end %>
    </ul>
  </li>
<% elsif topic.present? %>
  <!-- Render the individual community heading -->
  <li class="sidebar-item" data-item-id="<%= topic.id %>">
    <span class="sidebar-heading">
      <%= link_to topic.topic_name, communities_path(topic_id: topic.id), class: "community-link", data: { turbo: false}  %>
    </span>
  </li>
<% end %>

<script>
  function toggleChildren(arrow) {
    const subItems = arrow.closest('.sidebar-item').querySelector('.sub-items');
    subItems.classList.toggle('hidden');
  }
</script>

app/views/shared/_nested_topic.html.erb
<!-- app/views/shared/_nested_topic.html.erb -->

<% if topic.present? && topic.children.present? %>
  <li class="sidebar-item cursor-pointer" data-item-id="<%= topic.id %>">
    <span class="flex items-center justify-between">
      <span class="sidebar-heading">
        <span class="arrow-icon border-solid border border-t-4 border-transparent cursor-pointer" onclick="toggleChildren(this)">&#9654;</span>
        <%= link_to topic.topic_name, communities_path(topic_id: topic.id), class: "community-link", data: { turbo: false} %>
      </span>
    </span>
    <ul class="sub-items hidden pl-4">
      <% topic.children.each do |child_topic| %>
        <%= render 'shared/nested_topic', topic: child_topic %>
      <% end %>
    </ul>
  </li>
<% elsif topic.present? %>
  <!-- Render the individual community heading -->
  <li class="sidebar-item" data-item-id="<%= topic.id %>">
    <span class="sidebar-heading">
      <%= link_to topic.topic_name, communities_path(topic_id: topic.id), class: "community-link", data: { turbo: false} %>
    </span>
  </li>
<% end %>

<script>
  function toggleChildren(arrow) {
    const subItems = arrow.closest('.sidebar-item').querySelector('.sub-items');
    subItems.classList.toggle('hidden');
  }
</script>

app/views/shared/_nested_topic_connections.html.erb
<!-- app/views/shared/_nested_topic.html.erb -->

<% if topic.present? && topic.children.present? %>
  <li class="sidebar-item cursor-pointer" data-item-id="<%= topic.id %>">
    <span class="flex items-center justify-between">
      <span class="sidebar-heading">
        <span class="arrow-icon border-solid border border-t-4 border-transparent cursor-pointer" onclick="toggleChildren(this)">&#9654;</span>
        <%= link_to topic.topic_name, connection_path(id: topic.id), class: "community-link" %>
      </span>
    </span>
    <ul class="sub-items hidden pl-4">
      <% topic.children.each do |child_topic| %>
        <%= render 'shared/nested_topic_connections', topic: child_topic %>
      <% end %>
    </ul>
  </li>
<% elsif topic.present? %>
  <!-- Render the individual community heading -->
  <li class="sidebar-item" data-item-id="<%= topic.id %>">
    <span class="sidebar-heading">
      <%= link_to topic.topic_name, connection_path(id: topic.id), class: "community-link" %>
    </span>
  </li>
<% end %>

<script>
  function toggleChildren(arrow) {
    const subItems = arrow.closest('.sidebar-item').querySelector('.sub-items');
    subItems.classList.toggle('hidden');
  }
</script>

app/views/tweets/_controls.html.erb
<ul class="-ml-3 flex space-x-14 items-start justify-start list-none">
  <li>
    <%= link_to tweet, class: "text-gray-500 space-x-2 group flex items-center justify-center", data: { turbo: false } do %>
      <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-sky-50">
        <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current group-hover:text-sky-500"><g><path d="M14.046 2.242l-4.148-.01h-.002c-4.374 0-7.8 3.427-7.8 7.802 0 4.098 3.186 7.206 7.465 7.37v3.828c0 .108.044.286.12.403.142.225.384.347.632.347.138 0 .277-.038.402-.118.264-.168 6.473-4.14 8.088-5.506 1.902-1.61 3.04-3.97 3.043-6.312v-.017c-.006-4.367-3.43-7.787-7.8-7.788zm3.787 12.972c-1.134.96-4.862 3.405-6.772 4.643V16.67c0-.414-.335-.75-.75-.75h-.396c-3.66 0-6.318-2.476-6.318-5.886 0-3.534 2.768-6.302 6.3-6.302l4.147.01h.002c3.532 0 6.3 2.766 6.302 6.296-.003 1.91-.942 3.844-2.514 5.176z"></path></g></svg>
      </div>
      <%= turbo_frame_tag "#{dom_id(tweet)}_comments_count" do %>
        <%= render "tweets/comments_count", tweet: tweet %>
      <% end %>
    <% end %>
  </li>
  <% if user_signed_in? && tweet.user_id != current_user.id %>
    <li>
      <%= button_to retweet_tweet_path(tweet), method: :post, class:"text-gray-500 space-x-2 group flex items-center justify-center" do %>
        <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-green-50">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="w-5 h-5 fill-current group-hover:text-green-500"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>
        </div>
        <span class="group-hover:text-green-500 text-gray-500"><%= Tweet.where(tweet_id: tweet).count %></span>
      <% end %>
    </li>
  <% end %>
  <li>
    <%= content_tag :div, class: "#{dom_id(tweet)}_likes" do %>
      <%= render "likes/likes", likeable: tweet %>
    <% end %>
  </li>
  <% if user_signed_in? && current_user == tweet.user %>
    <li>
      <%= button_to tweet_path(tweet), method: :delete, form: { data: { turbo_confirm: "Are you sure?" }}, class:"text-gray-500 space-x-2 group flex items-center justify-center" do %>
        <div class="flex items-center justify-center w-10 h-10 rounded-full hover:bg-gray-50">
          <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-500 group-hover:text-rose-500 w-5 h-5"><g><path d="M20.746 5.236h-3.75V4.25c0-1.24-1.01-2.25-2.25-2.25h-5.5c-1.24 0-2.25 1.01-2.25 2.25v.986h-3.75c-.414 0-.75.336-.75.75s.336.75.75.75h.368l1.583 13.262c.216 1.193 1.31 2.027 2.658 2.027h8.282c1.35 0 2.442-.834 2.664-2.072l1.577-13.217h.368c.414 0 .75-.336.75-.75s-.335-.75-.75-.75zM8.496 4.25c0-.413.337-.75.75-.75h5.5c.413 0 .75.337.75.75v.986h-7V4.25zm8.822 15.48c-.1.55-.664.795-1.18.795H7.854c-.517 0-1.083-.246-1.175-.75L5.126 6.735h13.74L17.32 19.732z"></path><path d="M10 17.75c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75zm4 0c.414 0 .75-.336.75-.75v-7c0-.414-.336-.75-.75-.75s-.75.336-.75.75v7c0 .414.336.75.75.75z"></path></g></svg>
        </div>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/tweets/_form.html.erb
<%= form_with model: @tweet, data: { controller: "reset-form", action: "turbo:submit-end->reset-form#reset" } do |form|  %>
  <% if flash[:tweet_errors] %>
    <div class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3 mx-3">
      <ul>
        <% flash[:tweet_errors].each do |error| %>
          <li><%= error %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.text_area :body, class: "border-b border-t-0 border-x-0 mb-6 px-6 pt-6 block w-full border-gray-200 focus:shadow-none focus:outline-none focus:ring-transparent focus:border-gray-300 resize-none min-h-[180px] text-lg", placeholder: "What's on your mind?" %>

  <div class="flex justify-end px-6 -mt-20">
    <%= form.submit "Tweet", class: "px-6 py-2 bg-sky-400 text-white font-semibold rounded-full text-center cursor-pointer inline-block hover:bg-sky-500 transition ease-in-out duration-300"%>
  </div>
<% end %>

app/views/tweets/_retweet.html.erb
<div class="px-6 py-3 border-b" id="<%= dom_id(tweet) %>">
  <div class="flex items-center mb-3 space-x-2">
    <svg viewBox="0 0 24 24" aria-hidden="true" class="w-4 h-4 fill-current"><g><path d="M23.77 15.67c-.292-.293-.767-.293-1.06 0l-2.22 2.22V7.65c0-2.068-1.683-3.75-3.75-3.75h-5.85c-.414 0-.75.336-.75.75s.336.75.75.75h5.85c1.24 0 2.25 1.01 2.25 2.25v10.24l-2.22-2.22c-.293-.293-.768-.293-1.06 0s-.294.768 0 1.06l3.5 3.5c.145.147.337.22.53.22s.383-.072.53-.22l3.5-3.5c.294-.292.294-.767 0-1.06zm-10.66 3.28H7.26c-1.24 0-2.25-1.01-2.25-2.25V6.46l2.22 2.22c.148.147.34.22.532.22s.384-.073.53-.22c.293-.293.293-.768 0-1.06l-3.5-3.5c-.293-.294-.768-.294-1.06 0l-3.5 3.5c-.294.292-.294.767 0 1.06s.767.293 1.06 0l2.22-2.22V16.7c0 2.068 1.683 3.75 3.75 3.75h5.85c.414 0 .75-.336.75-.75s-.337-.75-.75-.75z"></path></g></svg>
    <p class="text-sm font-medium">Retweeted by <%= "@" + tweet.user.username %></p>
  </div>
  <div class="flex space-x-3 items-start">
    <div class="flex-shrink-0">
      <%= profile_image(tweet.tweet.user) %>
    </div>
    <div class="flex-1">
      <p class="font-bold"><%= link_to tweet.tweet.user.name, profile_path(tweet.tweet.user), class: "hover:underline", data: {turbo: false} %></p>
      <%= link_to tweet, data: { turbo: false } do %>
        <div class="prose prose-lg"><%= tweet.tweet.body %></div>
      <% end %>

      <%= render "tweets/controls", tweet: tweet.tweet %>
    </div>
  </div>
</div>

app/views/tweets/show.html.erb
<div class="p-6">
  <div class="flex items-center space-x-3">
    <%= link_to root_path, class: "rounded-full w-8 h-8 flex items-center justify-center hover:bg-gray-100 duration-300 transition-all" do %>
      <svg viewBox="0 0 24 24" aria-hidden="true" class="fill-current text-gray-800 w-5 h-5"><g><path d="M20 11H7.414l4.293-4.293c.39-.39.39-1.023 0-1.414s-1.023-.39-1.414 0l-6 6c-.39.39-.39 1.023 0 1.414l6 6c.195.195.45.293.707.293s.512-.098.707-.293c.39-.39.39-1.023 0-1.414L7.414 13H20c.553 0 1-.447 1-1s-.447-1-1-1z"></path></g></svg>
    <% end %>
    <h1 class="font-bold text-2xl">Tweet</h1>
  </div>
</div>

<div class="p-6">
  <div class="flex items-start justify-between space-x-3">
    <%= profile_image(@tweet.user) %>
    <div class="flex-1">
      <h1 class="font-bold">
        <%= link_to @tweet.user.name, profile_path(@tweet.user) %>
      </h1>
      <p class="text-gray-700"><%= "@" + @tweet.user.username %></p>
    </div>
  </div>
  <div class="prose prose-2xl text-gray-900 my-3">
    <% if @tweet.tweet_id? %>
      <%= @tweet.tweet.body %>
    <% else%>
      <%= @tweet.body %>
    <% end %>
  </div>

  <ul class="py-3 border-t text-gray-700 flex space-x-4 text-sm">
    <li>
      <span class="font-semibold text-gray-800"><%= Tweet.where(tweet_id: @tweet).size %></span> Retweets
    </li>
    <li>
      <span class="font-semibold text-gray-800"><%= @tweet.likes.size %></span> Likes
    </li>
  </ul>

  <div class="py-2 border-y px-4 justify-center flex">
    <%= render "tweets/controls", tweet: @tweet %>
  </div>

  <% if user_signed_in? %>
    <%= turbo_frame_tag "#{dom_id(@tweet)}_comment_form" do %>
      <%= render "comments/form", tweet: @tweet %>
    <% end %>
  <% else %>
    <p class="mt-6 text-center text-lg"><%= link_to "Sign in", new_user_session_path, class: "text-sky-500 hover:text-sky-600 font-medium" %></p>
  <% end %>

  <%= turbo_frame_tag "#{dom_id(@tweet)}_comments" do %>
    <% @comments.each do |comment| %>
      <%= render "comments/comment", comment: comment %>
    <% end %>
  <% end %>
</div>