config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :conversations
  resources :user_organizations
  resources :topics
  resources :organizations
  resources :moderators
  resources :communities
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :organizations do 
    resources :topics do
      resources :posts do     #These are for communities. Show all the posts in that community, irrespective of who follows who etc.
        resources :comments, only: [:create, :destroy]
        member do
          post :repost
        end
      end
    end
  end

  resources :feed
  
  resources :posts do         #All these are based on your feed. Can't show everything in the world at once
    patch 'moderation', on: :member
    resources :comments, only: [:create, :destroy]
    member do
      post 'update_options'
      get 'see_votes'
      post :repost
    end
  end
  

  resources :profiles do
    collection do
      get 'search'
    end
  end

  resources :likes, only: :create
  resources :connections do
    patch 'accept', on: :member
    resources :topics
  end

  resources :moderators
  get '/moderator/show_all/:user_id', to: 'moderators#show_all', as: 'moderator_show_all'


  resources :communities do
      post 'join_community', on: :collection
      resources :topics
  end

  resources :conversations do
    resources :messages
  end

  post 'switch_organization/:organization_id/:topic_id', to: 'organizations#switch_organization', as: :switch_organization
  post 'send_connection', to: 'connections#send_connection', as: 'send_connection'
  post '/add_moderator_request', to: 'moderators#add_moderator_request', as: 'add_moderator_request'
  patch '/add_moderator', to: 'moderators#add_moderator', as: 'add_moderator'
  get 'repost_posts', to: 'posts#repost_post', as: 'repost_posts'
  patch '/submit_repost', to: 'posts#submit_repost', as: 'submit_repost'
  get 'choose_posts', to: 'posts#choose', as: 'choose'

  #devise_for :users
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  root to: "feed#index"
end

app/models/organization.rb
class Organization < ApplicationRecord
    has_many :users
    has_many :communities
    has_many :user_organizations 
    has_many :moderators
    belongs_to :privacy
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  before_action :set_organization, only: %i[ show edit update destroy ]

  # GET /organizations or /organizations.json
  def index
    @organizations = Organization.all
  end

  # GET /organizations/1 or /organizations/1.json
  def show
  end

  # GET /organizations/new
  def new
    @organization = Organization.new
  end

  def switch_organization
    organization_id = params[:organization_id]
    # Perform validation or authorization checks if necessary
    # ...
    @profile = current_user
    indic = 0
    @profile.user_organizations.each do |user_organization|
      if user_organization.organization_id == organization_id.to_i
        session[:organization_id] = organization_id
        flash[:notice] = "Switched to organization #{user_organization.organization.organization_name}"
        indic = 1
      end
    end
    if indic == 0
      flash[:notice] = "You cannot access this organization yet."
    end
    redirect_back(fallback_location: root_path)
  end


  # GET /organizations/1/edit
  def edit 
  end

  # POST /organizations or /organizations.json
  def create
    @organization = Organization.new(organization_params)

    respond_to do |format|
      if @organization.save
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully created." }
        format.json { render :show, status: :created, location: @organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /organizations/1 or /organizations/1.json
  def update
    respond_to do |format|
      if @organization.update(organization_params)
        format.html { redirect_to organization_url(@organization), notice: "Organization was successfully updated." }
        format.json { render :show, status: :ok, location: @organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /organizations/1 or /organizations/1.json
  def destroy
    @organization.destroy

    respond_to do |format|
      format.html { redirect_to organizations_url, notice: "Organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_organization
      @organization = Organization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def organization_params
      params.require(:organization).permit(:organization_path, :organization_name, :organization_email)
    end
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/views/organizations/_form.html.erb
<%= form_with(model: organization, class: "contents") do |form| %>
  <% if organization.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(organization.errors.count, "error") %> prohibited this organization from being saved:</h2>

      <ul>
        <% organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :organization_path %>
    <%= form.text_field :organization_path, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :organization_name %>
    <%= form.text_field :organization_name, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :organization_email %>
    <%= form.text_field :organization_email, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/organizations/_organization.html.erb
<div id="<%= dom_id organization %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Organization path:</strong>
    <%= organization.organization_path %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Organization name:</strong>
    <%= organization.organization_name %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Organization email:</strong>
    <%= organization.organization_email %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this organization", organization, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this organization", edit_organization_path(organization), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/organizations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing organization</h1>

  <%= render "form", organization: @organization %>

  <%= link_to "Show this organization", @organization, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organizations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Organizations</h1>
    <%= link_to "New organization", new_organization_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="organizations" class="min-w-full">
    <%= render @organizations %>
  </div>
</div>

app/views/organizations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New organization</h1>

  <%= render "form", organization: @organization %>

  <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/organizations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @organization %>

    <%= link_to "Edit this organization", edit_organization_path(@organization), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this organization", organization_path(@organization), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to organizations", organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>