config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  resources :conversations
  resources :user_organizations
  resources :topics
  resources :organizations
  resources :moderators
  resources :communities
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  resources :organizations do 
    resources :topics do
      resources :posts do     #These are for communities. Show all the posts in that community, irrespective of who follows who etc.
        resources :comments, only: [:create, :destroy]
        member do
          post :repost
        end
      end
    end
  end

  resources :feed
  
  resources :posts do         #All these are based on your feed. Can't show everything in the world at once
    patch 'moderation', on: :member
    resources :comments, only: [:create, :destroy]
    member do
      post 'update_options'
      get 'see_votes'
      post :repost
    end
  end
  

  resources :profiles do
    collection do
      get 'search'
    end
  end

  resources :likes, only: :create
  resources :connections do
    patch 'accept', on: :member
    resources :topics
  end

  resources :moderators
  get '/moderator/show_all/:user_id', to: 'moderators#show_all', as: 'moderator_show_all'


  resources :communities do
      post 'join_community', on: :collection
      resources :topics
  end

  resources :conversations do
    resources :messages
  end

  post 'switch_organization/:organization_id/:topic_id', to: 'organizations#switch_organization', as: :switch_organization
  post 'send_connection', to: 'connections#send_connection', as: 'send_connection'
  post '/add_moderator_request', to: 'moderators#add_moderator_request', as: 'add_moderator_request'
  patch '/add_moderator', to: 'moderators#add_moderator', as: 'add_moderator'
  get 'repost_posts', to: 'posts#repost_post', as: 'repost_posts'
  patch '/submit_repost', to: 'posts#submit_repost', as: 'submit_repost'
  get 'choose_posts', to: 'posts#choose', as: 'choose'

  #devise_for :users
  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }
  root to: "feed#index"
end

app/models/user_organization.rb
class UserOrganization < ApplicationRecord
  belongs_to :user
  belongs_to :organization
end

app/controllers/user_organizations_controller.rb
class UserOrganizationsController < ApplicationController
  before_action :set_user_organization, only: %i[ show edit update destroy ]

  # GET /user_organizations or /user_organizations.json
  def index
    @user_organizations = UserOrganization.all
  end

  # GET /user_organizations/1 or /user_organizations/1.json
  def show
  end

  # GET /user_organizations/new
  def new     #Can add a new organization for yourself with a button
    @user_organization = UserOrganization.new
  end

  # GET /user_organizations/1/edit
  def edit
  end

  # POST /user_organizations or /user_organizations.json
  def create
    @user_organization = UserOrganization.new(user_organization_params)

    respond_to do |format|
      if @user_organization.save
        format.html { redirect_to user_organization_url(@user_organization), notice: "User organization was successfully created." }
        format.json { render :show, status: :created, location: @user_organization }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_organizations/1 or /user_organizations/1.json
  def update
    respond_to do |format|
      if @user_organization.update(user_organization_params)
        format.html { redirect_to user_organization_url(@user_organization), notice: "User organization was successfully updated." }
        format.json { render :show, status: :ok, location: @user_organization }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user_organization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_organizations/1 or /user_organizations/1.json
  def destroy
    @user_organization.destroy

    respond_to do |format|
      format.html { redirect_to user_organizations_url, notice: "User organization was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_organization
      @user_organization = UserOrganization.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_organization_params
      params.require(:user_organization).permit(:user_id, :organization_id)
    end
end

app/helpers/user_organizations_helper.rb
module UserOrganizationsHelper
end

app/views/user_organizations/_form.html.erb
<%= form_with(model: user_organization, class: "contents") do |form| %>
  <% if user_organization.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(user_organization.errors.count, "error") %> prohibited this user_organization from being saved:</h2>

      <ul>
        <% user_organization.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :organization_id %>
    <%= form.text_field :organization_id, class: "block shadow rounded-md border border-gray-200 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/user_organizations/_user_organization.html.erb
<div id="<%= dom_id user_organization %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">User:</strong>
    <%= user_organization.user_id %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Organization:</strong>
    <%= user_organization.organization_id %>
  </p>

  <% if action_name != "show" %>
    <%= link_to "Show this user organization", user_organization, class: "rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Edit this user organization", edit_user_organization_path(user_organization), class: "rounded-lg py-3 ml-2 px-5 bg-gray-100 inline-block font-medium" %>
    <hr class="mt-6">
  <% end %>
</div>

app/views/user_organizations/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing user organization</h1>

  <%= render "form", user_organization: @user_organization %>

  <%= link_to "Show this user organization", @user_organization, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to user organizations", user_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_organizations/index.html.erb
<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">User organizations</h1>
    <%= link_to "New user organization", new_user_organization_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="user_organizations" class="min-w-full">
    <%= render @user_organizations %>
  </div>
</div>

app/views/user_organizations/new.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">New user organization</h1>

  <%= render "form", user_organization: @user_organization %>

  <%= link_to "Back to user organizations", user_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/user_organizations/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex">
  <div class="mx-auto">
    <% if notice.present? %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <%= render @user_organization %>

    <%= link_to "Edit this user_organization", edit_user_organization_path(@user_organization), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this user_organization", user_organization_path(@user_organization), method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
    <%= link_to "Back to user_organizations", user_organizations_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  </div>
</div>